set SynModuleInfo {
  {SRCNAME LSTM_Top_Pipeline_VITIS_LOOP_10_1 MODELNAME LSTM_Top_Pipeline_VITIS_LOOP_10_1 RTLNAME LSTM_Top_LSTM_Top_Pipeline_VITIS_LOOP_10_1
    SUBMODULES {
      {MODELNAME LSTM_Top_flow_control_loop_pipe_sequential_init RTLNAME LSTM_Top_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME LSTM_Top_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME infer_Pipeline_1 MODELNAME infer_Pipeline_1 RTLNAME LSTM_Top_infer_Pipeline_1}
  {SRCNAME infer_Pipeline_2 MODELNAME infer_Pipeline_2 RTLNAME LSTM_Top_infer_Pipeline_2}
  {SRCNAME infer_Pipeline_3 MODELNAME infer_Pipeline_3 RTLNAME LSTM_Top_infer_Pipeline_3}
  {SRCNAME infer_Pipeline_4 MODELNAME infer_Pipeline_4 RTLNAME LSTM_Top_infer_Pipeline_4}
  {SRCNAME infer_Pipeline_5 MODELNAME infer_Pipeline_5 RTLNAME LSTM_Top_infer_Pipeline_5}
  {SRCNAME infer_Pipeline_6 MODELNAME infer_Pipeline_6 RTLNAME LSTM_Top_infer_Pipeline_6}
  {SRCNAME infer_Pipeline_VITIS_LOOP_107_2 MODELNAME infer_Pipeline_VITIS_LOOP_107_2 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_107_2}
  {SRCNAME infer_Pipeline_VITIS_LOOP_108_3 MODELNAME infer_Pipeline_VITIS_LOOP_108_3 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_108_3}
  {SRCNAME infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5 MODELNAME infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5
    SUBMODULES {
      {MODELNAME LSTM_Top_mac_muladd_8ns_8ns_8ns_15_4_1 RTLNAME LSTM_Top_mac_muladd_8ns_8ns_8ns_15_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5_Weight0_f_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5_Weight0_f_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5_Bias0_f_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_114_4_VITIS_LOOP_116_5_Bias0_f_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME infer_Pipeline_VITIS_LOOP_22_1 MODELNAME infer_Pipeline_VITIS_LOOP_22_1 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_22_1}
  {SRCNAME infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7 MODELNAME infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7
    SUBMODULES {
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7_Weight0_i_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7_Weight0_i_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7_Bias0_i_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_128_6_VITIS_LOOP_130_7_Bias0_i_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME infer_Pipeline_VITIS_LOOP_22_11 MODELNAME infer_Pipeline_VITIS_LOOP_22_11 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_22_11}
  {SRCNAME infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9 MODELNAME infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9
    SUBMODULES {
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9_Weight0_c_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9_Weight0_c_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9_Bias0_c_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_142_8_VITIS_LOOP_144_9_Bias0_c_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME infer_Pipeline_VITIS_LOOP_34_1 MODELNAME infer_Pipeline_VITIS_LOOP_34_1 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_34_1}
  {SRCNAME infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11 MODELNAME infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11
    SUBMODULES {
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11_Weight0_o_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11_Weight0_o_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11_Bias0_o_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_156_10_VITIS_LOOP_158_11_Bias0_o_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME infer_Pipeline_VITIS_LOOP_22_12 MODELNAME infer_Pipeline_VITIS_LOOP_22_12 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_22_12}
  {SRCNAME infer_Pipeline_VITIS_LOOP_170_12 MODELNAME infer_Pipeline_VITIS_LOOP_170_12 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_170_12}
  {SRCNAME infer_Pipeline_VITIS_LOOP_56_1 MODELNAME infer_Pipeline_VITIS_LOOP_56_1 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_56_1}
  {SRCNAME infer_Pipeline_VITIS_LOOP_56_13 MODELNAME infer_Pipeline_VITIS_LOOP_56_13 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_56_13}
  {SRCNAME infer_Pipeline_VITIS_LOOP_45_1 MODELNAME infer_Pipeline_VITIS_LOOP_45_1 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_45_1}
  {SRCNAME infer_Pipeline_VITIS_LOOP_181_13 MODELNAME infer_Pipeline_VITIS_LOOP_181_13 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_181_13}
  {SRCNAME infer_Pipeline_VITIS_LOOP_34_14 MODELNAME infer_Pipeline_VITIS_LOOP_34_14 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_34_14}
  {SRCNAME infer_Pipeline_VITIS_LOOP_56_15 MODELNAME infer_Pipeline_VITIS_LOOP_56_15 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_56_15}
  {SRCNAME infer_Pipeline_VITIS_LOOP_193_15 MODELNAME infer_Pipeline_VITIS_LOOP_193_15 RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_193_15
    SUBMODULES {
      {MODELNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_193_15_Weight_lc_0_ROM_AUTO_1R RTLNAME LSTM_Top_infer_Pipeline_VITIS_LOOP_193_15_Weight_lc_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME infer MODELNAME infer RTLNAME LSTM_Top_infer
    SUBMODULES {
      {MODELNAME LSTM_Top_faddfsub_32ns_32ns_32_5_full_dsp_1 RTLNAME LSTM_Top_faddfsub_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME LSTM_Top_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_fdiv_32ns_32ns_32_10_no_dsp_1 RTLNAME LSTM_Top_fdiv_32ns_32ns_32_10_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 9 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME LSTM_Top_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_fadd_32ns_32ns_32_5_full_dsp_1 RTLNAME LSTM_Top_fadd_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_gate_f_RAM_AUTO_1R1W RTLNAME LSTM_Top_infer_gate_f_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_C_t_RAM_AUTO_1R1W RTLNAME LSTM_Top_infer_C_t_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_infer_vec_i_RAM_AUTO_1R1W RTLNAME LSTM_Top_infer_vec_i_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME LSTM_Top MODELNAME LSTM_Top RTLNAME LSTM_Top IS_TOP 1
    SUBMODULES {
      {MODELNAME LSTM_Top_buf_in_RAM_AUTO_1R1W RTLNAME LSTM_Top_buf_in_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LSTM_Top_regslice_both RTLNAME LSTM_Top_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME LSTM_Top_regslice_both_U}
    }
  }
}
